[sdl]
fullscreen=false
autolock=false

[dosbox]
machine=svga_s3

[cpu]
core=auto
cputype=auto
cycles=3000

[sblaster]
sbtype=sb16
sbbase=220
irq=7
dma=1
hdma=5

[mixer]
rate=44100

[autoexec]
@echo off
mount c .
c:
BREAKIN.EXE
